#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>

#define BLACK "\033[0;30m"
#define GREEN "\033[0;32m"
#define RED "\033[0;31m"

#define FILE_WRITE "file_write"
#define FILE_FT_WRITE "file_ft_write"
#define FILE_READ "scatman_history"

#define BUFSIZE 10000
#define TEXT "Scatman is a song by Scatman John on his debut album Scatman's World"

size_t ft_strlen(const char *s);
char *ft_strcpy(char *restrict dst, const char *restrict src);
int ft_strcmp(const char *s1, const char *s2);
ssize_t ft_write(int fd, const void *buf, size_t count);
ssize_t ft_read(int fd, const void *buf, size_t count);
char *ft_strdup(const char *s1);

// 10'000 characters long
const char *long_string = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

void reset_errno() {
    errno = 0;
}

void print_errno() {
        printf("errno:\t%d\n", errno);
        reset_errno();
}

void print_test_name(char *test_name) {
  printf("%s****\t%s\t****\n\n%s", GREEN, test_name, BLACK);
}

void test_ft_strlen(void) {
  // STRLEN vs FT_STRLEN
  print_test_name("strlen vs ft_strlen");

  printf("strlen:\t\t%zu\n", strlen("Hello"));
  printf("ft_strlen:\t%zu\n\n", ft_strlen("Hello"));
  printf("strlen:\t\t%zu\n", strlen(""));
  printf("ft_strlen:\t%zu\n\n", ft_strlen(""));
  printf("strlen:\t\t%zu\n", strlen("42"));
  printf("ft_strlen:\t%zu\n\n", ft_strlen("42"));
  printf("strlen:\t\t%zu\n", strlen("Lorem ipsum dolor sit amet, consectetur adipiscing elit."));
  printf("ft_strlen:\t%zu\n\n", ft_strlen("Lorem ipsum dolor sit amet, consectetur adipiscing elit."));
  printf("strlen:\t\t%zu\n", strlen(long_string));
  printf("ft_strlen:\t%zu\n\n", ft_strlen(long_string));
}

void test_ft_strcpy(void) {
  // STRCPY vs FT_STRCPY
  print_test_name("strcpy vs ft_strcpy");

  char bufs_dst_strcpy[3][10001];
  char bufs_dst_ft_strcpy[3][10001];

  strcpy(bufs_dst_strcpy[0], "");
  ft_strcpy(bufs_dst_ft_strcpy[0], "");
  printf("%p bufs_dst_strcpy[0]:\t\t%s\n", bufs_dst_strcpy[0], bufs_dst_strcpy[0]);
  printf("%p bufs_dst_ft_strcpy[0]:\t%s\n\n", bufs_dst_ft_strcpy[0], bufs_dst_ft_strcpy[0]);

  strcpy(bufs_dst_strcpy[1], "42");
  ft_strcpy(bufs_dst_ft_strcpy[1], "42");
  printf("%p bufs_dst_strcpy[1]:\t%s\n", bufs_dst_strcpy[1], bufs_dst_strcpy[1]);
  printf("%p bufs_dst_ft_strcpy[1]\t%s\n\n", bufs_dst_ft_strcpy[1], bufs_dst_ft_strcpy[1]);

  strcpy(bufs_dst_strcpy[2], long_string);
  ft_strcpy(bufs_dst_ft_strcpy[2], long_string);
  printf("%p bufs_dst_strcpy[2]:\t%s\n", bufs_dst_strcpy[2], bufs_dst_strcpy[2]);
  printf("%p bufs_dst_ft_strcpy[2]:\t%s\n\n", bufs_dst_ft_strcpy[2], bufs_dst_ft_strcpy[2]);
}

void test_ft_strcmp(void) {
  // STRCMP vs FT_STRCMP
  print_test_name("strcmp vs ft_strcmp");

  printf("strcmp(Hello, Hello):\t\t%d\n", strcmp("Hello", "Hello"));
  printf("ft_strcmp(Hello, Hello):\t%d\n\n", ft_strcmp("Hello", "Hello"));
  printf("strcmp(Hello, World):\t\t%d\n", strcmp("Hello", "World"));
  printf("ft_strcmp(Hello, World):\t%d\n\n", ft_strcmp("Hello", "World"));
  printf("strcmp(World, Hello):\t\t%d\n", strcmp("World", "Hello"));
  printf("ft_strcmp(World, Hello):\t%d\n\n", ft_strcmp("World", "Hello"));
  printf("strcmp(Hello, 42):\t\t%d\n", strcmp("Hello", "42"));
  printf("ft_strcmp(Hello, 42):\t\t%d\n\n", ft_strcmp("Hello", "42"));
  printf("strcmp(42, 42):\t\t\t%d\n", strcmp("42", "42"));
  printf("ft_strcmp(42, 42):\t\t%d\n\n", ft_strcmp("42", "42"));
  printf("strcmp(42, 21):\t\t\t%d\n", strcmp("42", "21"));
  printf("ft_strcmp(42, 21):\t\t%d\n\n", ft_strcmp("42", "21"));
  printf("strcmp(42, ):\t\t\t%d\n", strcmp("42", ""));
  printf("ft_strcmp(42, ):\t\t%d\n\n", ft_strcmp("42", ""));
  printf("strcmp( , 42):\t\t\t%d\n", strcmp("", "42"));
  printf("ft_strcmp( , 42):\t\t%d\n\n", ft_strcmp("", "42"));
  printf("strcmp( , ):\t\t\t%d\n", strcmp("", ""));
  printf("ft_strcmp( , ):\t\t\t%d\n\n", ft_strcmp("", ""));
  printf("strcmp( \\xff\\xff, \\xff ):\t%d\n", strcmp("\xff\xff", "\xff"));
  printf("ft_strcmp( \\xff\\xff, \\xff ):\t%d\n\n", ft_strcmp("\xff\xff", "\xff"));
}

void open_files(int *fd_file_write, int *fd_file_ft_write) {
  *fd_file_write = open(FILE_WRITE, O_RDWR | O_CREAT | O_TRUNC, 0644);
  *fd_file_ft_write = open(FILE_FT_WRITE, O_RDWR | O_CREAT | O_TRUNC, 0644);

  if (*fd_file_write == -1) {
    printf("Error opening fd_file_write\n");
    exit(1);
  }
  if (*fd_file_ft_write == -1) {
    printf("Error opening fd_file_ft_write\n");
    exit(1);
  }
}

void close_files(const int *fd_file_write, const int *fd_file_ft_write) {
  close(*fd_file_write);
  close(*fd_file_ft_write);
}

void close_and_open_files(int *fd_file_write, int *fd_file_ft_write) {
  close_files(fd_file_write, fd_file_ft_write);
  open_files(fd_file_write, fd_file_ft_write);
}

void reset_test(int *fd_file_write, int *fd_file_ft_write) {
  close_and_open_files(fd_file_write, fd_file_ft_write);
  reset_errno();
}

void compare_files(int *fd_file_write, int *fd_file_ft_write) {
  char bufs_read[2][BUFSIZE + 1];

  memset(bufs_read[0], 0, sizeof(bufs_read[0]));
  memset(bufs_read[1], 0, sizeof(bufs_read[1]));
  lseek(*fd_file_write, 0, SEEK_SET);
  lseek(*fd_file_ft_write, 0, SEEK_SET);
  read(*fd_file_write, bufs_read[0], BUFSIZE);
  read(*fd_file_ft_write, bufs_read[1], BUFSIZE);
  printf("Comparing files: ");
  strcmp(bufs_read[0], bufs_read[1]) == 0 ? printf("%sFiles are equal\n\n%s", GREEN, BLACK) : printf("%sFiles are not equal\n\n%s", RED, BLACK);
}

void test_write_and_compare_files(int *fd_file_write, int *fd_file_ft_write, char *test_name, const char *buf, size_t count) {
  reset_test(fd_file_write, fd_file_ft_write);
  printf("write %s:\treturn value:\t%zd\t\t", test_name, write(*fd_file_write, buf, count));
  print_errno();
  printf("ft_write %s:\treturn value:\t%zd\t\t", test_name, ft_write(*fd_file_ft_write, buf, count));
  print_errno();
  compare_files(fd_file_write, fd_file_ft_write);
}

void test_ft_write(void) {
  // WRITE vs FT_WRITE
  print_test_name("write vs ft_write");

  int fd_file_write;
  int fd_file_ft_write;

  test_write_and_compare_files(&fd_file_write, &fd_file_ft_write, "long_string in file", long_string,BUFSIZE);
  test_write_and_compare_files(&fd_file_write, &fd_file_ft_write, "empty string in file", "", 0);
  test_write_and_compare_files(&fd_file_write, &fd_file_ft_write, "3 bytes in file", "ABCDEFG", 3);
  test_write_and_compare_files(&fd_file_write, &fd_file_ft_write, "1 byte in file", "A", 1);
  test_write_and_compare_files(&fd_file_write, &fd_file_ft_write, "0 bytes in file", "", 0);
  test_write_and_compare_files(&fd_file_write, &fd_file_ft_write, "1 byte from empty buffer", "", 1);

  // Test with invalid file descriptor
  reset_test(&fd_file_write, &fd_file_ft_write);
  printf("write fd_invalid:\treturn value:\t%zd\t\t", write(-1, long_string, BUFSIZE));
  print_errno();
  printf("ft_write fd_invalid:\treturn value:\t%zd\t\t", ft_write(-1, long_string, BUFSIZE));
  print_errno();
  compare_files(&fd_file_write, &fd_file_ft_write);

  // Test write in STDOUT
  reset_test(&fd_file_write, &fd_file_ft_write);
  printf("write STDOUT:\treturn value:\t%zd\t\t", write(STDOUT_FILENO, "\tLorem ipsum in in STDOUT\n", 27));
  print_errno();
  printf("ft_write STDOUT:\treturn value:\t%zd\t\t", ft_write(STDOUT_FILENO, "\tLorem ipsum in STDOUT\n", 27));
  print_errno();
  compare_files(&fd_file_write, &fd_file_ft_write);

  close_files(&fd_file_write, &fd_file_ft_write);
  remove(FILE_WRITE);
  remove(FILE_FT_WRITE);
}

void run_read_test_case(int fd, char *test_case) {
  char buf[2][10000];

  memset(buf[0], 0, sizeof(buf[0]));
  memset(buf[1], 0, sizeof(buf[1]));
  lseek(fd, 0, SEEK_SET);
  reset_errno();
  printf("read %s: %s\treturn value:\t%zd\t\t", test_case, buf[0], read(fd, buf[0], BUFSIZE));
  print_errno();
  lseek(fd, 0, SEEK_SET);
  reset_errno();
  printf("ft_read %s: %s\treturn value:\t%zd\t\t", test_case, buf[1], ft_read(fd, buf[1], BUFSIZE));
  print_errno();
  printf("\n");
}

void test_ft_read(void) {
  // READ vs FT_READ
  print_test_name("read vs ft_read");

  const int fd_file_read = open(FILE_READ, O_RDWR | O_CREAT | O_TRUNC, 0644);
  write(fd_file_read, TEXT, strlen(TEXT));

  run_read_test_case(fd_file_read, FILE_READ);
  run_read_test_case(-1, "from invalid file descriptor");
  run_read_test_case(STDIN_FILENO, "from STDIN");

  close(fd_file_read);
  remove(FILE_READ);
}

void run_strdup_test_case(const char *str) {
  char *str1 = strdup(str);
  char *str2 = ft_strdup(str);
  strcmp(str1, str2) == 0 ? printf("%sstrdup and ft_strdup are equal%s\n", GREEN, BLACK) : printf("%sstrdup and ft_strdup are not equal%s\n", RED, BLACK);
  printf("str1: %s\n", str1);
  printf("str2: %s\n\n", str2);
  free(str1);
  free(str2);
}

void test_ft_strdup(void) {
  // STRDUP vs FT_STRDUP
  print_test_name("strdup vs ft_strdup");

  run_strdup_test_case("");
  run_strdup_test_case("Hello, World!");
  run_strdup_test_case("42");
  run_strdup_test_case(long_string);
}

int main (){
        test_ft_strlen();
        test_ft_strcpy();
        test_ft_strcmp();
        test_ft_write();
        test_ft_read();
        test_ft_strdup();

        return 0;
}
